apiVersion: v1
kind: Service
metadata:
  name: agent-state
spec:
  selector:
    app: agent-state
  ports:
    - protocol: TCP
      port: {{ .Values.agentState.port }}
      targetPort: {{ .Values.agentState.port }}
  type: ClusterIP
