apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-state
spec:
  replicas: {{ .Values.agentState.replicas }}
  selector:
    matchLabels:
      app: agent-state
  template:
    metadata:
      labels:
        app: agent-state
    spec:
      containers:
        - name: agent-state
          image: {{ .Values.agentState.image }}
          ports:
            - containerPort: {{ .Values.agentState.port }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.agentState.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.agentState.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
