apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: {{ .Values.authService.replicas }}
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: {{ .Values.authService.image }}
          ports:
            - containerPort: {{ .Values.authService.port }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.authService.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.authService.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
