apiVersion: apps/v1
kind: Deployment
metadata:
  name: interaction-service
spec:
  replicas: {{ .Values.interactionService.replicas }}
  selector:
    matchLabels:
      app: interaction-service
  template:
    metadata:
      labels:
        app: interaction-service
    spec:
      containers:
        - name: interaction-service
          image: {{ .Values.interactionService.image }}
          ports:
            - containerPort: {{ .Values.interactionService.port }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.interactionService.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.interactionService.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
