apiVersion: v1
kind: Service
metadata:
  name: interaction-service
spec:
  selector:
    app: interaction-service
  ports:
    - protocol: TCP
      port: {{ .Values.interactionService.port }}
      targetPort: {{ .Values.interactionService.port }}
  type: ClusterIP
