apiVersion: v1
kind: Pod
metadata:
  name: test-auth-to-agent
  annotations:
    "helm.sh/hook": test
spec:
  containers:
  - name: curl
    image: curlimages/curl:latest
    command: ["curl"]
    args: ["http://agent-state:8081/health"]
  restartPolicy: Never